### ISSUE TITLE
g4 instance works for the first time, but cannot be properly recreated from AMI

### ISSUE THREAD

**Issue by machacd** [jamesstringerparsec/Parsec-Cloud-Preparation-Tool#16]
When I run the instance for the first time and use the script exactly as described, all works great. But when I save this instance into an AMI, after recreating it, the resolution is fixed to 1280*1024. 

* I am using the latest Nvidia Gaming AMI as a base
* I have tried skipping the GPU update step, to no avail

Might be related to #13 with the difference that all works good for the first time.

**Comment by jamesstringerparsec** [comment]
These scripts aren't intended to be converted into a AMI so I haven't tested the functionality

**Comment by steventhegeek** [comment]
I would test it but the some of the NVidia AMIs are broken as of the 442.19 release today. Looks like they forgot to embed the Amazon security stuff again. I'll certainly try imaging of a vanilla 2019 AMI with the parsec scripts running and see what happens.

**Comment by jamesstringerparsec** [comment]
Just note that if you do create an AMI from the Parsec Cloud Prep Tool (this repo) the password will be baked in to the AMI.

In addition there are also some static routes that need to be removed before AMI creation, these static routes are region specific, and will completely prevent AMIs copied to other regions from working.

If you're building a G4 based AMI and have used GPU updater tool to install the driver, also run `Remove-AWSCredentialProfile -ProfileName GPUUpdateG4Dn` to remove the AWS credential from the machine, otherwise everyone will have access to your AWS account (BAD).

**Comment by machacd** [comment]
I am the sole user of the AMI, so the baked in credentials are not a big deal. 

If a custom AMI creation is not supported, Is there another option how to launch a spot instance without having to setup everything each time?

**Comment by jamesstringerparsec** [comment]
> I am the sole user of the AMI, so the baked in credentials should not matter (right?).
> 
> If a custom AMI creation is not supported, Is there another option how to launch a spot instance without having to setup everything each time?

Not right now

**Comment by steventhegeek** [comment]
It works fine with a vanilla 2016 server instead of using the Nvidia Gaming. I think you are accidentally using NVidias initialisation script and messing up the drivers after sysprep. Given how bad NVidia are at creating AMI's, I'd suggest not using those images anyway as a general rule. All they have over vanilla is the Nvidia SDK which is downloadable after free registration to the Nvidia developer site.

**Comment by machacd** [comment]
Steven, it works for me as well, thank you!

It is basically the oposite of this advice:
```
Q. My cloud machine is stuck at 1366x768
A. You should delete your machine and use the GRID Virtual Workstation variety provided by your cloud provider (it's a check box on GCP)
```

**Comment by steventhegeek** [comment]
It seems that way but not really. The Grid Virtual workstation are talking
about the official images from the cloud provider with the drivers/Grid
License installed. So Azure, Paperspace & Google all have these when you
deploy a GPU machine. It's just AWS that's a little different. NVidia AMI
is just a third party machine. That message seems specific to Google cloud.

**Comment by aegixx** [comment]
FWIW I'm using a combination of an AMI created with this tool along with https://github.com/cloudrig/CloudRIG to launch a ready-made cloud machine using Spot Instance pricing.  It works awesome!
